import { getPrisma } from "@/lib/prisma";
import { serializeEvent, type EventDTO } from "@/lib/events";
import { classifyEvent, enrichEventWithClassification } from "@/lib/event-classification";
import {
  detectConflicts,
  getConflictCounters,
  getConflictEventIds,
  type Conflict,
  type ConflictFilter,
  type ConflictSeverity,
  matchesConflictFilter,
} from "@/lib/conflicts";

const SEVERITY_RANK: Record<ConflictSeverity, number> = { high: 0, medium: 1, low: 2 };
const BATCH_SIZE = 40;

function sortConflicts(conflicts: Conflict[]): Conflict[] {
  return [...conflicts].sort(
    (a, b) =>
      SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity] ||
      (a.date ?? "").localeCompare(b.date ?? "")
  );
}

function toConflictRecord(
  row: {
    id: string;
    eventAId: string;
    eventBId: string;
    conflictType: string;
    severity: string;
    reasons: string;
    recommendation: string;
    resolutionStatus: string;
    resolutionNotes: string;
    pairKey: string;
    isAutoGenerated: boolean;
    eventA: Parameters<typeof serializeEvent>[0];
    eventB: Parameters<typeof serializeEvent>[0];
  }
): Conflict | null {
  if (!row.eventA || !row.eventB) return null;
  const eventA = serializeEvent(row.eventA);
  const eventB = serializeEvent(row.eventB);
  let reasons: string[] = [];
  try {
    reasons = JSON.parse(row.reasons) as string[];
  } catch {
    reasons = row.reasons ? [row.reasons] : [];
  }

  return {
    id: row.id,
    pairKey: row.pairKey,
    type: row.conflictType as Conflict["type"],
    severity: row.severity as Conflict["severity"],
    reasons,
    message: reasons[0] ?? row.recommendation,
    reason: reasons[0] ?? row.recommendation,
    recommendedAction: row.recommendation,
    recommendation: row.recommendation,
    events: [eventA, eventB],
    resolutionStatus: row.resolutionStatus,
    resolutionNotes: row.resolutionNotes,
    isAutoGenerated: row.isAutoGenerated,
    date: eventA.startDate <= eventB.startDate ? eventB.startDate : eventA.startDate,
    host1: eventA.host,
    host2: eventB.host,
    venue1: eventA.location,
    venue2: eventB.location,
  };
}

export async function getStoredConflicts(filters?: ConflictFilter[]): Promise<Conflict[]> {
  const prisma = getPrisma();
  const rows = await prisma.eventConflict.findMany({
    include: { eventA: true, eventB: true },
    orderBy: { updatedAt: "desc" },
  });

  let conflicts = rows
    .map(toConflictRecord)
    .filter((c): c is Conflict => c !== null);

  if (filters?.length) {
    conflicts = conflicts.filter((c) => filters.some((f) => matchesConflictFilter(c, f)));
  }
  return sortConflicts(conflicts);
}

export function computeLiveConflicts(events: EventDTO[]): Conflict[] {
  const classified = events.map((e) => enrichEventWithClassification(e));
  return sortConflicts(detectConflicts(classified));
}

async function loadClassifiedEvents(): Promise<EventDTO[]> {
  const prisma = getPrisma();
  const events = await prisma.event.findMany({
    orderBy: [{ startDate: "asc" }, { title: "asc" }],
  });
  return events.map((e) => enrichEventWithClassification(serializeEvent(e)));
}

function buildSummary(conflicts: Conflict[], source: "stored" | "live", eventCount: number) {
  const counters = getConflictCounters(conflicts);
  return {
    conflicts,
    counters,
    defaultConflicts: conflicts.filter(
      (c) =>
        c.resolutionStatus === "unresolved" &&
        (c.severity === "high" || c.severity === "medium")
    ),
    conflictEventIds: getConflictEventIds(conflicts),
    count: counters.defaultView,
    source,
    eventCount,
    persisted: source === "stored",
  };
}

export async function getConflictSummary() {
  const prisma = getPrisma();
  const eventCount = await prisma.event.count();

  try {
    const stored = await getStoredConflicts();
    if (stored.length > 0 || eventCount === 0) {
      return buildSummary(stored, "stored", eventCount);
    }
  } catch {
    // Table may not exist yet — fall through to live compute.
  }

  const classified = await loadClassifiedEvents();
  const live = computeLiveConflicts(classified);
  return buildSummary(live, "live", eventCount);
}

export async function recalculateConflicts(): Promise<{
  deleted: number;
  created: number;
  preserved: number;
  total: number;
}> {
  const prisma = getPrisma();
  const rawEvents = await prisma.event.findMany();
  const classifiedEvents: EventDTO[] = [];

  for (let i = 0; i < rawEvents.length; i += BATCH_SIZE) {
    const chunk = rawEvents.slice(i, i + BATCH_SIZE);
    await prisma.$transaction(
      chunk.map((row) => {
        const dto = serializeEvent(row);
        const classification = classifyEvent(dto);
        const enriched = { ...dto, ...classification };
        classifiedEvents.push(enriched);
        return prisma.event.update({
          where: { id: row.id },
          data: classification,
        });
      })
    );
  }

  const detected = detectConflicts(classifiedEvents);
  const eventMap = new Map(classifiedEvents.map((e) => [e.id, e]));

  const existing = await prisma.eventConflict.findMany();
  const preservedKeys = new Set<string>();

  for (const row of existing) {
    if (!row.isAutoGenerated) {
      preservedKeys.add(row.pairKey);
      continue;
    }
    if (["resolved", "dismissed", "related_events"].includes(row.resolutionStatus)) {
      const eventA = eventMap.get(row.eventAId);
      const eventB = eventMap.get(row.eventBId);
      const unchanged =
        eventA &&
        eventB &&
        row.eventAUpdatedAt &&
        row.eventBUpdatedAt &&
        new Date(eventA.updatedAt).getTime() === row.eventAUpdatedAt.getTime() &&
        new Date(eventB.updatedAt).getTime() === row.eventBUpdatedAt.getTime();
      if (unchanged) {
        preservedKeys.add(row.pairKey);
      }
    }
  }

  const deleteResult = await prisma.eventConflict.deleteMany({
    where: {
      isAutoGenerated: true,
      pairKey: { notIn: Array.from(preservedKeys) },
    },
  });

  const toCreate = detected
    .filter((c) => !preservedKeys.has(c.pairKey))
    .map((conflict) => {
      const [eventA, eventB] = conflict.events;
      return {
        eventAId: eventA.id,
        eventBId: eventB.id,
        conflictType: conflict.type,
        severity: conflict.severity,
        reasons: JSON.stringify(conflict.reasons),
        recommendation: conflict.recommendation,
        resolutionStatus: "unresolved",
        pairKey: conflict.pairKey,
        isAutoGenerated: true,
        eventAUpdatedAt: new Date(eventA.updatedAt),
        eventBUpdatedAt: new Date(eventB.updatedAt),
      };
    });

  let created = 0;
  for (let i = 0; i < toCreate.length; i += BATCH_SIZE) {
    const batch = toCreate.slice(i, i + BATCH_SIZE);
    const result = await prisma.eventConflict.createMany({ data: batch });
    created += result.count;
  }

  const total = await prisma.eventConflict.count();
  return { deleted: deleteResult.count, created, preserved: preservedKeys.size, total };
}

export async function getEventsForConflictEngine(): Promise<EventDTO[]> {
  return loadClassifiedEvents();
}

/** Nav badge: unresolved high + medium conflicts. */
export async function getConflictBadgeCount(): Promise<number> {
  try {
    const summary = await getConflictSummary();
    return summary.count;
  } catch {
    return 0;
  }
}

export async function getConflictEventIdList(): Promise<string[]> {
  try {
    const summary = await getConflictSummary();
    return Array.from(summary.conflictEventIds);
  } catch {
    return [];
  }
}
