import { getPrisma } from "@/lib/prisma";
import { serializeEvent, type EventDTO } from "@/lib/events";
import { classifyEvent } from "@/lib/event-classification";
import {
  detectConflicts,
  getConflictCounters,
  getConflictEventIds,
  type Conflict,
  type ConflictFilter,
  matchesConflictFilter,
} from "@/lib/conflicts";

function toConflictRecord(
  row: {
    id: string;
    eventAId: string;
    eventBId: string;
    conflictType: string;
    severity: string;
    reasons: string;
    recommendation: string;
    resolutionStatus: string;
    resolutionNotes: string;
    pairKey: string;
    isAutoGenerated: boolean;
    eventA: Parameters<typeof serializeEvent>[0];
    eventB: Parameters<typeof serializeEvent>[0];
  }
): Conflict {
  const eventA = serializeEvent(row.eventA);
  const eventB = serializeEvent(row.eventB);
  let reasons: string[] = [];
  try {
    reasons = JSON.parse(row.reasons) as string[];
  } catch {
    reasons = row.reasons ? [row.reasons] : [];
  }

  return {
    id: row.id,
    pairKey: row.pairKey,
    type: row.conflictType as Conflict["type"],
    severity: row.severity as Conflict["severity"],
    reasons,
    message: reasons[0] ?? row.recommendation,
    reason: reasons[0] ?? row.recommendation,
    recommendedAction: row.recommendation,
    recommendation: row.recommendation,
    events: [eventA, eventB],
    resolutionStatus: row.resolutionStatus,
    resolutionNotes: row.resolutionNotes,
    isAutoGenerated: row.isAutoGenerated,
    date: eventA.startDate <= eventB.startDate ? eventB.startDate : eventA.startDate,
    host1: eventA.host,
    host2: eventB.host,
    venue1: eventA.location,
    venue2: eventB.location,
  };
}

export async function getStoredConflicts(filters?: ConflictFilter[]): Promise<Conflict[]> {
  const prisma = getPrisma();
  const rows = await prisma.eventConflict.findMany({
    include: { eventA: true, eventB: true },
    orderBy: [{ severity: "asc" }, { updatedAt: "desc" }],
  });

  let conflicts = rows.map(toConflictRecord);
  if (filters?.length) {
    conflicts = conflicts.filter((c) => filters.some((f) => matchesConflictFilter(c, f)));
  }
  return conflicts;
}

export async function getConflictSummary() {
  const conflicts = await getStoredConflicts();
  const counters = getConflictCounters(conflicts);
  return {
    conflicts,
    counters,
    defaultConflicts: conflicts.filter(
      (c) =>
        c.resolutionStatus === "unresolved" &&
        (c.severity === "high" || c.severity === "medium")
    ),
    conflictEventIds: getConflictEventIds(conflicts),
    count: counters.defaultView,
  };
}

export async function recalculateConflicts(): Promise<{
  deleted: number;
  created: number;
  preserved: number;
  total: number;
}> {
  const prisma = getPrisma();
  const events = (await prisma.event.findMany()).map(serializeEvent);

  for (const event of events) {
    const classification = classifyEvent(event);
    await prisma.event.update({
      where: { id: event.id },
      data: classification,
    });
  }

  const classifiedEvents = (await prisma.event.findMany()).map(serializeEvent);
  const detected = detectConflicts(classifiedEvents);
  const eventMap = new Map(classifiedEvents.map((e) => [e.id, e]));

  const existing = await prisma.eventConflict.findMany();
  const preservedKeys = new Set<string>();

  for (const row of existing) {
    if (!row.isAutoGenerated) {
      preservedKeys.add(row.pairKey);
      continue;
    }
    if (["resolved", "dismissed", "related_events"].includes(row.resolutionStatus)) {
      const eventA = eventMap.get(row.eventAId);
      const eventB = eventMap.get(row.eventBId);
      const unchanged =
        eventA &&
        eventB &&
        row.eventAUpdatedAt &&
        row.eventBUpdatedAt &&
        new Date(eventA.updatedAt).getTime() === row.eventAUpdatedAt.getTime() &&
        new Date(eventB.updatedAt).getTime() === row.eventBUpdatedAt.getTime();
      if (unchanged) {
        preservedKeys.add(row.pairKey);
      }
    }
  }

  const deleteResult = await prisma.eventConflict.deleteMany({
    where: {
      isAutoGenerated: true,
      pairKey: { notIn: Array.from(preservedKeys) },
    },
  });

  let created = 0;
  let preserved = preservedKeys.size;

  for (const conflict of detected) {
    if (preservedKeys.has(conflict.pairKey)) continue;

    const [eventA, eventB] = conflict.events;
    await prisma.eventConflict.upsert({
      where: { pairKey: conflict.pairKey },
      create: {
        eventAId: eventA.id,
        eventBId: eventB.id,
        conflictType: conflict.type,
        severity: conflict.severity,
        reasons: JSON.stringify(conflict.reasons),
        recommendation: conflict.recommendation,
        resolutionStatus: "unresolved",
        pairKey: conflict.pairKey,
        isAutoGenerated: true,
        eventAUpdatedAt: new Date(eventA.updatedAt),
        eventBUpdatedAt: new Date(eventB.updatedAt),
      },
      update: {
        conflictType: conflict.type,
        severity: conflict.severity,
        reasons: JSON.stringify(conflict.reasons),
        recommendation: conflict.recommendation,
        isAutoGenerated: true,
        eventAUpdatedAt: new Date(eventA.updatedAt),
        eventBUpdatedAt: new Date(eventB.updatedAt),
      },
    });
    created++;
  }

  const total = await prisma.eventConflict.count();
  return { deleted: deleteResult.count, created, preserved, total };
}

export async function getEventsForConflictEngine(): Promise<EventDTO[]> {
  const prisma = getPrisma();
  const events = await prisma.event.findMany({
    orderBy: [{ startDate: "asc" }, { title: "asc" }],
  });
  return events.map(serializeEvent);
}
