import type { EventDTO } from "./events";
import {
  isBroadVenue,
  normalizeHost,
  normalizeTargetGroup,
  normalizeTitle,
  normalizeVenue,
} from "./event-classification";

export type ConflictType =
  | "same_venue_overlapping_time"
  | "same_venue_time_missing"
  | "same_host_overlapping_time"
  | "same_host_time_missing"
  | "participant_overlapping_time"
  | "participant_time_missing"
  | "major_blocking_conflict"
  | "holiday_conflict"
  | "duplicate_event"
  | "possible_duplicate"
  | "schedule_verification"
  | "low_notice";

export type ConflictSeverity = "high" | "medium" | "low";

export type ConflictCandidate = {
  conflictType: ConflictType;
  severity: ConflictSeverity;
  reason: string;
  recommendation: string;
};

export type Conflict = {
  id?: string;
  pairKey: string;
  type: ConflictType;
  severity: ConflictSeverity;
  reasons: string[];
  message: string;
  reason: string;
  recommendedAction: string;
  recommendation: string;
  events: EventDTO[];
  resolutionStatus: string;
  resolutionNotes: string;
  isAutoGenerated: boolean;
  date?: string;
  location?: string;
  host1?: string;
  host2?: string;
  venue1?: string;
  venue2?: string;
};

export type ConflictFilter =
  | "confirmed"
  | "needs_verification"
  | "same_venue"
  | "same_host"
  | "same_participants"
  | "major_calendar"
  | "holiday_scheduling"
  | "possible_duplicate"
  | "low_notice"
  | "ignored_resolved";

const SEVERITY_RANK: Record<ConflictSeverity, number> = { high: 0, medium: 1, low: 2 };

const RELATED_TYPES = new Set([
  "coverage",
  "support",
  "booth",
  "publication",
  "preparation",
  "component",
  "companion",
]);

const MAJOR_BLOCKING_KEYWORDS =
  /university days|university hinampang|\bsldp\b|university-wide exam|final examination|midterm examination|commencement|baccalaureate|recognition ceremon|mandatory orientation|no-activity period|suspension of classes/i;

function datesOverlap(a: EventDTO, b: EventDTO): boolean {
  return a.startDate <= b.endDate && b.startDate <= a.endDate;
}

function sameCalendarDay(a: EventDTO, b: EventDTO): boolean {
  return a.startDate === b.startDate && a.endDate === b.endDate;
}

function hasTimeData(event: EventDTO): boolean {
  return Boolean(event.startTime?.trim() && event.endTime?.trim());
}

function timesOverlap(a: EventDTO, b: EventDTO): boolean | null {
  if (!hasTimeData(a) || !hasTimeData(b)) return null;
  const toMin = (t: string) => {
    const [h, m] = t.split(":").map(Number);
    return h * 60 + (m || 0);
  };
  const aStart = toMin(a.startTime);
  const aEnd = toMin(a.endTime);
  const bStart = toMin(b.startTime);
  const bEnd = toMin(b.endTime);
  return aStart < bEnd && bStart < aEnd;
}

function isPhysicalDelivery(event: EventDTO): boolean {
  return (
    event.deliveryMode === "onsite" ||
    event.deliveryMode === "hybrid" ||
    (event.deliveryMode === "unspecified" && Boolean(event.venueNormalized))
  );
}

function isOnlineDelivery(event: EventDTO): boolean {
  return (
    event.deliveryMode === "online_synchronous" ||
    event.deliveryMode === "online_asynchronous" ||
    event.deliveryMode === "hybrid"
  );
}

function venueConflictPossible(a: EventDTO, b: EventDTO): boolean {
  const venueA = a.venueNormalized || normalizeVenue(a.location);
  const venueB = b.venueNormalized || normalizeVenue(b.location);
  const broadA = !venueA || isBroadVenue(a.location);
  const broadB = !venueB || isBroadVenue(b.location);

  if (broadA && broadB) return false;
  if (broadA || broadB) return false;
  return venueA === venueB;
}

function sameHost(a: EventDTO, b: EventDTO): boolean {
  const hostA = a.hostNormalized || normalizeHost(a.host);
  const hostB = b.hostNormalized || normalizeHost(b.host);
  return Boolean(hostA && hostB && hostA === hostB);
}

function sameParticipants(a: EventDTO, b: EventDTO): boolean {
  const pa = a.targetGroupNormalized || normalizeTargetGroup(a.targetParticipants);
  const pb = b.targetGroupNormalized || normalizeTargetGroup(b.targetParticipants);
  if (!pa || !pb) return false;
  if (pa === "all students" && pb === "all students") return true;
  return pa === pb || pa.includes(pb) || pb.includes(pa);
}

function isHoliday(event: EventDTO): boolean {
  return event.recordType === "holiday" || event.category === "National Holiday";
}

function isMajorBlockingEvent(event: EventDTO): boolean {
  if (event.isMajorBlockingEvent) return true;
  const text = `${event.title} ${event.description}`;
  if (!MAJOR_BLOCKING_KEYWORDS.test(text)) return false;
  if (/\bsldp\b/i.test(text)) {
    return event.participationRequired || /required|mandatory/i.test(event.targetParticipants);
  }
  return true;
}

function areRelatedEvents(a: EventDTO, b: EventDTO): boolean {
  if (a.parentEventId === b.id || b.parentEventId === a.id) return true;
  if (a.parentEventId && a.parentEventId === b.parentEventId) return true;
  const relA = a.relationType ?? "independent";
  const relB = b.relationType ?? "independent";
  return relA !== "independent" && relB !== "independent" && RELATED_TYPES.has(relA);
}

function isLowNotice(event: EventDTO): boolean {
  if (!["Proposed", "Pending Approval", "Needs Verification"].includes(event.status)) {
    return false;
  }
  const today = new Date().toISOString().slice(0, 10);
  const daysUntil = Math.floor(
    (new Date(`${event.startDate}T00:00:00Z`).getTime() - new Date(`${today}T00:00:00Z`).getTime()) /
      86400000
  );
  return daysUntil >= 0 && daysUntil <= 14;
}

function overlapAnchorDate(a: EventDTO, b: EventDTO): string {
  return a.startDate <= b.startDate ? b.startDate : a.startDate;
}

function makePairKey(idA: string, idB: string): string {
  return idA < idB ? `${idA}:${idB}` : `${idB}:${idA}`;
}

function orderedPair(a: EventDTO, b: EventDTO): [EventDTO, EventDTO] {
  return a.id < b.id ? [a, b] : [b, a];
}

function mergeCandidates(candidates: ConflictCandidate[]): ConflictCandidate | null {
  if (candidates.length === 0) return null;
  return candidates.sort((x, y) => SEVERITY_RANK[x.severity] - SEVERITY_RANK[y.severity])[0];
}

function buildMessage(primary: ConflictCandidate, a: EventDTO, b: EventDTO): string {
  switch (primary.conflictType) {
    case "duplicate_event":
      return `Duplicate: "${a.title}" and "${b.title}"`;
    case "possible_duplicate":
      return `Possible duplicate: "${a.title}" / "${b.title}"`;
    case "same_venue_overlapping_time":
      return `Venue conflict at ${a.location}`;
    case "same_venue_time_missing":
      return `Same venue, time unconfirmed: ${a.location}`;
    case "same_host_overlapping_time":
      return `${a.host} has overlapping schedules`;
    case "same_host_time_missing":
      return `${a.host} has same-day activities (time unconfirmed)`;
    case "participant_overlapping_time":
    case "participant_time_missing":
      return `Participant overlap: ${a.targetParticipants || b.targetParticipants}`;
    case "major_blocking_conflict":
      return `Org activity overlaps major university blocking event`;
    case "holiday_conflict":
      return `Activity scheduled during ${isHoliday(a) ? a.title : b.title}`;
    case "schedule_verification":
      return `Schedule verification needed (venue TBA)`;
    case "low_notice":
      return `Low-notice scheduling: ${a.title} / ${b.title}`;
    default:
      return primary.reason;
  }
}

export function evaluatePair(a: EventDTO, b: EventDTO): ConflictCandidate[] {
  if (a.status === "Cancelled" || b.status === "Cancelled") return [];
  if (!a.conflictEligible || !b.conflictEligible) return [];
  if (!datesOverlap(a, b)) return [];

  const related = areRelatedEvents(a, b);
  const candidates: ConflictCandidate[] = [];
  const timeOverlap = timesOverlap(a, b);
  const sameVenue = venueConflictPossible(a, b);
  const bothBroadVenue =
    isBroadVenue(a.location) &&
    isBroadVenue(b.location) &&
    !(a.venueNormalized || normalizeVenue(a.location)) &&
    !(b.venueNormalized || normalizeVenue(b.location));

  const hostMatch = sameHost(a, b);
  const participantMatch = sameParticipants(a, b);
  const physicalA = isPhysicalDelivery(a);
  const physicalB = isPhysicalDelivery(b);
  const onlineOnlyPair =
    isOnlineDelivery(a) &&
    isOnlineDelivery(b) &&
    !physicalA &&
    !physicalB &&
    a.deliveryMode !== "hybrid" &&
    b.deliveryMode !== "hybrid";

  // Duplicate detection (always evaluated)
  if (
    hostMatch &&
    normalizeTitle(a.title) === normalizeTitle(b.title) &&
    a.startDate === b.startDate &&
    a.endDate === b.endDate &&
    sameVenue
  ) {
    candidates.push({
      conflictType: "duplicate_event",
      severity: "high",
      reason: "Same host, title, date range, and venue.",
      recommendation: "Remove or merge duplicate records.",
    });
  } else if (
    hostMatch &&
    normalizeTitle(a.title).slice(0, 24) === normalizeTitle(b.title).slice(0, 24) &&
    sameCalendarDay(a, b)
  ) {
    candidates.push({
      conflictType: "possible_duplicate",
      severity: "medium",
      reason: "Similar titles, same host, same date.",
      recommendation: "Verify details and merge if identical.",
    });
  }

  if (related) {
    if (sameVenue && timeOverlap === true) {
      candidates.push({
        conflictType: "same_venue_overlapping_time",
        severity: "high",
        reason: "Related events share a venue at overlapping times (operational conflict).",
        recommendation: "Confirm logistics for related activities.",
      });
    }
    return candidates;
  }

  // Venue conflicts — physical or hybrid with shared specific venue
  if (sameVenue && !onlineOnlyPair) {
    if (timeOverlap === true) {
      candidates.push({
        conflictType: "same_venue_overlapping_time",
        severity: "high",
        reason: `Both events use "${a.location}" at overlapping times.`,
        recommendation: "Reschedule one event or change venue.",
      });
    } else if (timeOverlap === null && sameCalendarDay(a, b)) {
      candidates.push({
        conflictType: "same_venue_time_missing",
        severity: "medium",
        reason: "Same venue and date but time is missing for one or both events.",
        recommendation: "Add times and verify whether schedules truly overlap.",
      });
    }
  }

  // Both TBA — schedule verification only
  if (bothBroadVenue && sameCalendarDay(a, b) && !hostMatch) {
    candidates.push({
      conflictType: "schedule_verification",
      severity: "low",
      reason: "Both events share a date with unspecified venues.",
      recommendation: "Confirm venues and times before treating as a conflict.",
    });
  }

  // Online vs physical — no venue conflict unless same exact times + same required participants
  if (
    ((physicalA && isOnlineDelivery(b)) || (physicalB && isOnlineDelivery(a))) &&
    participantMatch &&
    timeOverlap === true &&
    (a.participationRequired || b.participationRequired)
  ) {
    candidates.push({
      conflictType: "participant_overlapping_time",
      severity: "high",
      reason: "Required participants cannot attend overlapping online and onsite events.",
      recommendation: "Adjust schedule or confirm participants can split attendance.",
    });
  }

  // Same host conflicts
  if (hostMatch && !onlineOnlyPair) {
    if (timeOverlap === true) {
      candidates.push({
        conflictType: "same_host_overlapping_time",
        severity: "high",
        reason: "Same host cannot be in two places at once at overlapping times.",
        recommendation: "Adjust schedule or confirm different teams handle each activity.",
      });
    } else if (timeOverlap === null && sameCalendarDay(a, b)) {
      candidates.push({
        conflictType: "same_host_time_missing",
        severity: "medium",
        reason: "Same host has multiple activities on the same day without confirmed times.",
        recommendation: "Add times to confirm whether activities truly overlap.",
      });
    }
  }

  // Participant conflicts (not broad all-students unless times overlap)
  if (participantMatch) {
    const specificGroup =
      (a.targetGroupNormalized || normalizeTargetGroup(a.targetParticipants)) !== "all students";
    if (timeOverlap === true && (specificGroup || a.participationRequired || b.participationRequired)) {
      candidates.push({
        conflictType: "participant_overlapping_time",
        severity: "high",
        reason: "Both events target the same participants at overlapping times.",
        recommendation: "Confirm whether participants can attend both or reschedule.",
      });
    } else if (timeOverlap === null && sameCalendarDay(a, b) && specificGroup) {
      candidates.push({
        conflictType: "participant_time_missing",
        severity: "medium",
        reason: "Same participant group on the same day with unconfirmed times.",
        recommendation: "Add times and verify attendance feasibility.",
      });
    }
  }

  // Major blocking — NOT auto USC Events; explicit blocking only
  const orgEvent = [a, b].find((e) => e.category.startsWith("Org/CSC"));
  const blockingEvent = [a, b].find((e) => isMajorBlockingEvent(e));
  if (orgEvent && blockingEvent && orgEvent.id !== blockingEvent.id) {
    const orgTime = orgEvent.id === a.id ? a : b;
    const blockTime = blockingEvent.id === a.id ? a : b;
    const blockTimeOverlap = timesOverlap(orgTime, blockTime);
    if (blockTimeOverlap !== false) {
      candidates.push({
        conflictType: "major_blocking_conflict",
        severity: blockTimeOverlap === true ? "high" : "medium",
        reason: `"${orgEvent.title}" overlaps "${blockingEvent.title}" (${blockingEvent.category}).`,
        recommendation: "Verify with USC/college council whether org activity should be rescheduled.",
      });
    }
  }

  // Holiday scheduling
  const holiday = [a, b].find(isHoliday);
  const nonHoliday = [a, b].find((e) => !isHoliday(e));
  if (holiday && nonHoliday && nonHoliday.category.startsWith("Org/CSC")) {
    candidates.push({
      conflictType: "holiday_conflict",
      severity: "medium",
      reason: `"${nonHoliday.title}" is scheduled during ${holiday.title}.`,
      recommendation: "Flag for verification — do not auto-delete.",
    });
  }

  // Low notice
  if (isLowNotice(a) || isLowNotice(b)) {
    if (sameCalendarDay(a, b) && (hostMatch || sameVenue || participantMatch)) {
      candidates.push({
        conflictType: "low_notice",
        severity: "low",
        reason: "At least one event is proposed or pending with less than two weeks notice.",
        recommendation: "Confirm approval timeline and stakeholder notice.",
      });
    }
  }

  return candidates;
}

export function detectConflicts(events: EventDTO[]): Conflict[] {
  const eligible = events.filter((e) => e.status !== "Cancelled" && e.conflictEligible !== false);
  const sorted = [...eligible].sort(
    (x, y) => x.startDate.localeCompare(y.startDate) || x.id.localeCompare(y.id)
  );

  const pairMap = new Map<string, { events: [EventDTO, EventDTO]; candidates: ConflictCandidate[] }>();

  for (let i = 0; i < sorted.length; i++) {
    const a = sorted[i];
    for (let j = i + 1; j < sorted.length; j++) {
      const b = sorted[j];
      if (b.startDate > a.endDate) break;

      const candidates = evaluatePair(a, b);
      if (candidates.length === 0) continue;

      const [eventA, eventB] = orderedPair(a, b);
      const pairKey = makePairKey(eventA.id, eventB.id);
      const existing = pairMap.get(pairKey);
      if (existing) {
        existing.candidates.push(...candidates);
      } else {
        pairMap.set(pairKey, { events: [eventA, eventB], candidates });
      }
    }
  }

  const conflicts: Conflict[] = [];

  for (const [pairKey, { events: [eventA, eventB], candidates }] of pairMap) {
    const primary = mergeCandidates(candidates);
    if (!primary) continue;

    const reasons = [...new Set(candidates.map((c) => c.reason))];
    const overlapDate = overlapAnchorDate(eventA, eventB);

    conflicts.push({
      pairKey,
      type: primary.conflictType,
      severity: primary.severity,
      reasons,
      message: buildMessage(primary, eventA, eventB),
      reason: primary.reason,
      recommendedAction: primary.recommendation,
      recommendation: primary.recommendation,
      events: [eventA, eventB],
      resolutionStatus: "unresolved",
      resolutionNotes: "",
      isAutoGenerated: true,
      date: overlapDate,
      location: eventA.location === eventB.location ? eventA.location : undefined,
      host1: eventA.host,
      host2: eventB.host,
      venue1: eventA.location,
      venue2: eventB.location,
    });
  }

  return conflicts.sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]);
}

export function matchesConflictFilter(conflict: Conflict, filter: ConflictFilter): boolean {
  switch (filter) {
    case "confirmed":
      return conflict.events.every((e) => e.status === "Approved");
    case "needs_verification":
      return (
        conflict.type === "schedule_verification" ||
        conflict.events.some((e) => e.status === "Needs Verification")
      );
    case "same_venue":
      return conflict.type.startsWith("same_venue");
    case "same_host":
      return conflict.type.startsWith("same_host");
    case "same_participants":
      return conflict.type.startsWith("participant");
    case "major_calendar":
      return conflict.type === "major_blocking_conflict";
    case "holiday_scheduling":
      return conflict.type === "holiday_conflict";
    case "possible_duplicate":
      return conflict.type === "possible_duplicate" || conflict.type === "duplicate_event";
    case "low_notice":
      return conflict.type === "low_notice";
    case "ignored_resolved":
      return ["resolved", "dismissed", "related_events"].includes(conflict.resolutionStatus);
    default:
      return true;
  }
}

export function getConflictCounters(conflicts: Conflict[]) {
  const unresolved = conflicts.filter((c) => c.resolutionStatus === "unresolved");
  return {
    high: unresolved.filter((c) => c.severity === "high").length,
    medium: unresolved.filter((c) => c.severity === "medium").length,
    low: unresolved.filter((c) => c.severity === "low").length,
    needsVerification: conflicts.filter((c) => matchesConflictFilter(c, "needs_verification")).length,
    resolved: conflicts.filter((c) =>
      ["resolved", "dismissed", "related_events"].includes(c.resolutionStatus)
    ).length,
    total: conflicts.length,
    defaultView: unresolved.filter((c) => c.severity === "high" || c.severity === "medium").length,
  };
}

export function getConflictEventIds(conflicts: Conflict[]): Set<string> {
  const ids = new Set<string>();
  for (const conflict of conflicts) {
    if (conflict.resolutionStatus !== "unresolved") continue;
    if (conflict.severity === "low") continue;
    for (const event of conflict.events) ids.add(event.id);
  }
  return ids;
}
