"use server";

import { revalidatePath } from "next/cache";
import { getPrisma } from "@/lib/prisma";
import { isAdminAuthenticated } from "@/lib/auth";
import { recalculateConflicts, pruneStaleTbaConflicts } from "@/lib/conflict-queries";

async function requireAdmin() {
  const authed = await isAdminAuthenticated();
  if (!authed) throw new Error("Unauthorized");
}

export type ResolutionStatus =
  | "unresolved"
  | "reviewing"
  | "resolved"
  | "dismissed"
  | "related_events";

export async function resolveConflictAction(
  conflictId: string,
  status: ResolutionStatus,
  notes = ""
): Promise<{ success: boolean; error?: string }> {
  try {
    await requireAdmin();
    const prisma = getPrisma();
    await prisma.eventConflict.update({
      where: { id: conflictId },
      data: {
        resolutionStatus: status,
        resolutionNotes: notes,
        resolvedBy: "admin",
        resolvedAt: new Date(),
        isAutoGenerated: false,
      },
    });
    revalidatePath("/conflicts");
    revalidatePath("/admin");
    return { success: true };
  } catch (error) {
    console.error("resolveConflictAction:", error);
    return { success: false, error: "Failed to update conflict." };
  }
}

export async function changeConflictSeverityAction(
  conflictId: string,
  severity: "high" | "medium" | "low"
): Promise<{ success: boolean; error?: string }> {
  try {
    await requireAdmin();
    const prisma = getPrisma();
    await prisma.eventConflict.update({
      where: { id: conflictId },
      data: { severity, isAutoGenerated: false, resolvedBy: "admin", resolvedAt: new Date() },
    });
    revalidatePath("/conflicts");
    return { success: true };
  } catch (error) {
    console.error("changeConflictSeverityAction:", error);
    return { success: false, error: "Failed to change severity." };
  }
}

export async function linkRelatedEventsAction(
  childEventId: string,
  parentEventId: string,
  relationType: string
): Promise<{ success: boolean; error?: string }> {
  try {
    await requireAdmin();
    const prisma = getPrisma();
    await prisma.event.update({
      where: { id: childEventId },
      data: { parentEventId, relationType },
    });

    const conflicts = await prisma.eventConflict.findMany({
      where: {
        OR: [
          { eventAId: childEventId, eventBId: parentEventId },
          { eventAId: parentEventId, eventBId: childEventId },
        ],
      },
    });

    for (const conflict of conflicts) {
      await prisma.eventConflict.update({
        where: { id: conflict.id },
        data: {
          resolutionStatus: "related_events",
          resolutionNotes: `Linked as ${relationType}`,
          isAutoGenerated: false,
          resolvedBy: "admin",
          resolvedAt: new Date(),
        },
      });
    }

    revalidatePath("/conflicts");
    revalidatePath("/admin/events");
    return { success: true };
  } catch (error) {
    console.error("linkRelatedEventsAction:", error);
    return { success: false, error: "Failed to link related events." };
  }
}

export async function recalculateConflictsAction(): Promise<{
  success: boolean;
  error?: string;
  stats?: Awaited<ReturnType<typeof recalculateConflicts>>;
}> {
  try {
    await requireAdmin();
    await pruneStaleTbaConflicts();
    const stats = await recalculateConflicts();
    revalidatePath("/");
    revalidatePath("/calendar");
    revalidatePath("/organizations");
    revalidatePath("/conflicts");
    revalidatePath("/admin");
    return { success: true, stats };
  } catch (error) {
    console.error("recalculateConflictsAction:", error);
    return { success: false, error: "Failed to recalculate conflicts." };
  }
}
