-- AlterTable: new Event classification fields
ALTER TABLE "Event" ADD COLUMN "isMajorBlockingEvent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "conflictEligible" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Event" ADD COLUMN "dateType" TEXT NOT NULL DEFAULT 'exact';
ALTER TABLE "Event" ADD COLUMN "deliveryMode" TEXT NOT NULL DEFAULT 'unspecified';
ALTER TABLE "Event" ADD COLUMN "recordType" TEXT NOT NULL DEFAULT 'event';
ALTER TABLE "Event" ADD COLUMN "parentEventId" TEXT;
ALTER TABLE "Event" ADD COLUMN "relationType" TEXT NOT NULL DEFAULT 'independent';
ALTER TABLE "Event" ADD COLUMN "participationRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "venueNormalized" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN "hostNormalized" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN "targetGroupNormalized" TEXT NOT NULL DEFAULT '';

-- CreateTable: persisted conflicts
CREATE TABLE "EventConflict" (
    "id" TEXT NOT NULL,
    "eventAId" TEXT NOT NULL,
    "eventBId" TEXT NOT NULL,
    "conflictType" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "reasons" TEXT NOT NULL DEFAULT '[]',
    "recommendation" TEXT NOT NULL DEFAULT '',
    "resolutionStatus" TEXT NOT NULL DEFAULT 'unresolved',
    "resolutionNotes" TEXT NOT NULL DEFAULT '',
    "pairKey" TEXT NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "resolvedBy" TEXT NOT NULL DEFAULT '',
    "resolvedAt" TIMESTAMP(3),
    "eventAUpdatedAt" TIMESTAMP(3),
    "eventBUpdatedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EventConflict_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "EventConflict_pairKey_key" ON "EventConflict"("pairKey");
CREATE INDEX "EventConflict_severity_idx" ON "EventConflict"("severity");
CREATE INDEX "EventConflict_resolutionStatus_idx" ON "EventConflict"("resolutionStatus");
CREATE INDEX "EventConflict_conflictType_idx" ON "EventConflict"("conflictType");
CREATE INDEX "EventConflict_eventAId_idx" ON "EventConflict"("eventAId");
CREATE INDEX "EventConflict_eventBId_idx" ON "EventConflict"("eventBId");
CREATE INDEX "Event_endDate_idx" ON "Event"("endDate");
CREATE INDEX "Event_conflictEligible_idx" ON "Event"("conflictEligible");
CREATE INDEX "Event_parentEventId_idx" ON "Event"("parentEventId");

-- AddForeignKey
ALTER TABLE "Event" ADD CONSTRAINT "Event_parentEventId_fkey" FOREIGN KEY ("parentEventId") REFERENCES "Event"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EventConflict" ADD CONSTRAINT "EventConflict_eventAId_fkey" FOREIGN KEY ("eventAId") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EventConflict" ADD CONSTRAINT "EventConflict_eventBId_fkey" FOREIGN KEY ("eventBId") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;
